#!/usr/bin/env node


var mandolin_helper = require( "./mandolin-helper" )
  , mandolin   = new mandolin_helper()
  , pth_src    = "/Users/fritz/Documents/CAPTAIN_MANDOLIN/MUSIC"
  , pth_target = "/Volumes/SD/MUSIC"
  , files
  , bash_command
  , files_ready  = []
  , final_list   = []
  , songs_files  = []
  , must_haves   = []
  , fillers      = []
  , spoken_de = []
  , epics_de = []
  , epicsGrouped_de = []
  , spoken_it = []
  , epics_it = []
  , epicsGrouped_it = []
  , spoken_en = []
  , epics_en = []
  , epicsGrouped_en = []
  , spoken_files = []
  , epic_files = []
  , counter = 0
  , reEpics = "^\\d\\d\\d .+\.mp3$"
  , bash_file = "bash_file.sh"
  ;

files = mandolin.collectFiles( pth_src );
mandolin.logToFile( "files", files );

file_list = mandolin.asFileMoveList( files, pth_target );
mandolin.logToFile( "file_list", file_list );

files_ready = mandolin.shuffle( file_list );
mandolin.logToFile( "files_ready", files_ready );

final_list = mandolin.prepareFinalList( files_ready, pth_target );
mandolin.logToFile( "final_list", final_list );

bash_command = mandolin.generateBash( bash_file, final_list, pth_target )

process.exit(0);

